# Generated by Django 5.0.4 on 2024-05-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_gestin_humana'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='gestin_humana',
            new_name='gestion_humana',
        ),
    ]
