# Generated by Django 5.0.4 on 2024-05-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_rename_gestin_humana_empleado_gestion_humana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
